defaults.url=https://sentry.io/
defaults.org=brellatech
defaults.project=react-native
# Using SENTRY_AUTH_TOKEN environment variable
auth.token=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
